# In GKE need to get RBAC permissions first with
# kubectl create clusterrolebinding cluster-admin-binding --clusterrole=cluster-admin [--user=<user-name>|--group=<group-name>]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: clean-pods

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: clean-pods
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create","delete","get","list","patch","update","watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: clean-pods
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: clean-pods
subjects:
- kind: ServiceAccount
  name: clean-pods
